name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3  
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3 
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: |
        cd $GITHUB_WORKSPACE
        echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties
        ./gradlew clean build -x test
        cd $GITHUB_WORKSPACE/build/libs
    
    - name: Login to docker hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build docker image
      run: docker build -t dudwns9426/rmsoft-image .
      
    - name: Publish image to docker hub
      run: docker push dudwns9426/rmsoft-image:latest
      
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        docker-version: '24.0.7'

    - name: Pull Image from docker hub
      run: docker pull dudwns9426/rmsoft-image:latest
      
    - name: Delete old container
      run: docker rm -f rmsoft-container  
      
    - name: Run docker container
      run: docker run -d -p 8088:8088 --name rmsoft-container dudwns9426/rmsoft-image
